### ISSUE TITLE
Help with deploying

### ISSUE THREAD

**Issue by olszak94** [pandaac/pandaac#5]
Hi, i tried to deploy that acc, and i'm stuck on rewriting / htaccess, main webpage loads, but sub-pages like login or worlds or highscores, they wont load. Giving error 404 not found.

**Comment by eklundchristopher** [comment]
Which version of the AAC? Master branch or Apolune? if Apolune, it is not ready for production, it is missing a lot of the vital features.

**Comment by olszak94** [comment]
Apolune. We're trying to use it with TFS 1.2, is Master branch ready to use it with 1.2 ?

**Comment by eklundchristopher** [comment]
I've only tested it with TFS 1.1 so far, but I strongly recommend against using Apolune in production at the moment.

As for the master branch, it's only been tested with TFS 1.0. The master branch is no longer in active development, apart for security updates. 

It's a shame, but I'd recommend another AAC for the time being, until further progress has been made.

**Comment by olszak94** [comment]
k, thx
