### ISSUE TITLE
Where is the dummydata.json?

### ISSUE THREAD

**Issue by diorgesl** [pandaac/pandaac#8]

**Comment by eklundchristopher** [comment]
dummydata.json has been split up into several separated files instead. Sorry for the inconvenience, but remember, we haven't met a stable version yet so breaking changes are bound to happen.

They now reside within the storage folder, under [/storage/countries.json](https://github.com/pandaac/pandaac/blob/apolune/storage/countries.json) and [/storage/server/*](https://github.com/pandaac/pandaac/tree/apolune/storage/server).

**Edit:** I've updated the README to mention this.
